config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root to: 'users#index'

  resources :users do
  	collection do
  		put 'status'
  	end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/user.rb
class User < ApplicationRecord
  enum status: [:active, :desactive]

  def self.active_all(users)
	User.where("id IN (?)",users).update_all("status = 0")
  end

  def self.desactive_all(users)
  	User.where("id IN (?)",users).update_all("status = 1")
  end

  def self.order_by_id
  	order(:id)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  
  def index
    @users = User.order_by_id
  end

  def status
  	if params[:status] == 'active' && params[:users]
  		User.active_all(params[:users])
  	elsif params[:status] == 'desactive' && params[:users]
		  User.desactive_all(params[:users])
  	end

    redirect_to users_path
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>DemoUser</title>
    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>


  </head>

  <body>
  	<div class="container">  		
    	<%= yield %>
	</div>
  </body>
</html>

app/views/users/_user.haml
%tr
  %th
    = check_box_tag 'users[]', user.id, false ,id: "checkbox_#{dom_id user}", class: 'checkbox-of-table'
    = label_tag :selected, '', for: "checkbox_#{dom_id user}"
  %td= user.id
  %td= user.name
  %td= user.email
  %td= user.status

app/views/users/index.haml
= form_tag status_users_path, method: :put do
  = hidden_field_tag :status, '', id: 'action_hidden'
  .row
    .col.s12.m2
      %a{href: "#", class: 'btn blue top-space status-btn', "data-status": 'active'}
        Active
    .col.s12.m2
      %a{href: "#", class: 'btn blue top-space status-btn', "data-status": 'desactive'}
        Desactive

  %table
    %thead
      %tr
        %th
          %input{type: 'checkbox', id: 'all_users', class: 'all-checkbox-of-table', checked: false}
          %label{for: "all_users"}
        %th ID
        %th Name
        %th Email
        %th Status
    %tbody#users_index
      = render @users